using System;
using global::Avalonia.Controls;
using global::Avalonia.Interactivity;
using global::Avalonia.Platform.Storage;
using FEBuilderGBA.Avalonia.Services;
using FEBuilderGBA.Avalonia.ViewModels;

namespace FEBuilderGBA.Avalonia.Views
{
    /// <summary>
    /// Make-Patch text dialog for the Add-via-ASM/C tool — the Avalonia port of the
    /// shared WinForms <c>GraphicsToolPatchMakerForm</c>. It displays the
    /// redistributable patch-definition text generated by
    /// <see cref="AsmCompileCore.MakePatchText"/> for the last successful compile, and
    /// lets the user save it as a <c>PATCH_(NAME).txt</c> file (the
    /// <c>&lt;&lt;PATCH NAME&gt;&gt;</c> placeholder is filled in from the chosen file
    /// name on save). Read-only display + Save + Close — it reads no ROM bytes.
    ///
    /// Opened by <c>ToolASMInsertView</c> via <c>SetPatchText(...)</c> then
    /// <c>ShowDialog(owner)</c> (WF <c>f.Init(patch); f.ShowDialog();</c>).
    /// </summary>
    public partial class AsmPatchTextView : TranslatedWindow
    {
        readonly AsmPatchTextViewModel _vm = new();

        public AsmPatchTextView()
        {
            InitializeComponent();
            DataContext = _vm;
        }

        /// <summary>
        /// Set the patch-definition text shown by this dialog (WF
        /// <c>GraphicsToolPatchMakerForm.Init</c>). Call before <c>ShowDialog</c>.
        /// </summary>
        public void SetPatchText(string patchText)
        {
            _vm.Load(patchText);
        }

        async void Save_Click(object? sender, RoutedEventArgs e)
        {
            try
            {
                var storage = GetTopLevel(this)?.StorageProvider;
                if (storage == null) return;

                var file = await storage.SaveFilePickerAsync(new FilePickerSaveOptions
                {
                    Title = R._("Please select a file name to save."),
                    // WF defaults the picker name to PATCH_(NAME).txt; the user replaces
                    // "(NAME)" with the patch name, and the stem (minus PATCH_) becomes
                    // the NAME= value substituted on save.
                    SuggestedFileName = "PATCH_(NAME).txt",
                    FileTypeChoices = new[]
                    {
                        new FilePickerFileType(R._("Text Files")) { Patterns = new[] { "*.txt" } },
                        new FilePickerFileType(R._("All Files")) { Patterns = new[] { "*" } },
                    },
                });

                string? path = file?.TryGetLocalPath();
                if (!string.IsNullOrEmpty(path))
                {
                    if (_vm.Save(path))
                        Close();
                }
            }
            catch (Exception ex)
            {
                Log.Error("AsmPatchTextView.Save failed: " + ex.ToString());
                _vm.StatusMessage = R._("Failed to save the patch file.") + "\r\n" + ex.Message;
            }
        }

        void Close_Click(object? sender, RoutedEventArgs e) => Close();
    }
}
