using System;
using global::Avalonia.Controls;
using global::Avalonia.Interactivity;
using global::Avalonia.Platform.Storage;
using FEBuilderGBA.Avalonia.Services;
using FEBuilderGBA.Avalonia.ViewModels;
using FEBuilderGBA.Avalonia.Dialogs;

namespace FEBuilderGBA.Avalonia.Views
{
    /// <summary>
    /// Make-Patch text dialog for the Add-via-ASM/C tool — the Avalonia port of the
    /// shared WinForms <c>GraphicsToolPatchMakerForm</c>. It displays the
    /// redistributable patch-definition text generated by
    /// <see cref="AsmCompileCore.MakePatchText"/> for the last successful compile, and
    /// lets the user save it as a <c>PATCH_(NAME).txt</c> file (the
    /// <c>&lt;&lt;PATCH NAME&gt;&gt;</c> placeholder is filled in from the chosen file
    /// name on save). Read-only display + Save + Close — it reads no ROM bytes.
    ///
    /// Opened by <c>ToolASMInsertView</c> via <c>SetPatchText(...)</c> then
    /// <c>ShowDialog(owner)</c> (WF <c>f.Init(patch); f.ShowDialog();</c>).
    /// </summary>
    public partial class AsmPatchTextView : TranslatedUserControl, IEmbeddableEditor
    {
        public string ViewTitle => "Make Patch";
        public new bool IsLoaded => true;
        public EditorDescriptor Descriptor => new("Make Patch", 640, 520);
        public event EventHandler? CloseRequested;
        public void RequestClose() => CloseRequested?.Invoke(this, EventArgs.Empty);
        public void NavigateTo(uint address) { }

        readonly AsmPatchTextViewModel _vm = new();

        public AsmPatchTextView()
        {
            InitializeComponent();
            DataContext = _vm;
        }

        /// <summary>
        /// Set the patch-definition text shown by this dialog (WF
        /// <c>GraphicsToolPatchMakerForm.Init</c>). Call before <c>ShowDialog</c>.
        /// </summary>
        public void SetPatchText(string patchText)
        {
            _vm.Load(patchText);
        }

        async void Save_Click(object? sender, RoutedEventArgs e)
        {
            try
            {
                var storage = TopLevel.GetTopLevel(this)?.StorageProvider;
                if (storage == null) return;

                var file = await storage.SaveFilePickerAsync(new FilePickerSaveOptions
                {
                    Title = R._("Please select a file name to save."),
                    // WF defaults the picker name to PATCH_(NAME).txt; the user replaces
                    // "(NAME)" with the patch name, and the stem (minus PATCH_) becomes
                    // the NAME= value substituted on save.
                    SuggestedFileName = "PATCH_(NAME).txt",
                    FileTypeChoices = new[]
                    {
                        new FilePickerFileType(R._("Text Files")) { Patterns = new[] { "*.txt" } },
                        new FilePickerFileType(R._("All Files")) { Patterns = new[] { "*" } },
                    },
                });

                if (file != null)
                {
                    // #1639: write via the SAF bridge so Android content:// targets
                    // (no local path) are written through OpenWriteAsync. The patch
                    // NAME is derived from the file the user chose (file.Name), not
                    // the temp path, so the PATCH_ stem logic still works.
                    string nameSource = file.Name ?? "PATCH.txt";
                    bool ok = false;
                    string? written = await FileDialogHelper.WriteViaAsync(file, p => { ok = _vm.Save(p, nameSource); });
                    if (written != null && ok)
                        RequestClose();
                }
            }
            catch (Exception ex)
            {
                Log.Error("AsmPatchTextView.Save failed: " + ex.ToString());
                _vm.StatusMessage = R._("Failed to save the patch file.") + "\r\n" + ex.Message;
            }
        }

        void Close_Click(object? sender, RoutedEventArgs e) => RequestClose();
    }
}
