using System;
using System.Collections.Generic;
using System.IO;
using System.Text;
using global::Avalonia.Controls;
using global::Avalonia.Interactivity;
using global::Avalonia.Platform.Storage;
using FEBuilderGBA.Avalonia.Dialogs;
using FEBuilderGBA.Avalonia.Services;
using FEBuilderGBA.Avalonia.ViewModels;

namespace FEBuilderGBA.Avalonia.Views
{
    public partial class ToolExportEAEventView : Window, IEditorView
    {
        readonly ToolExportEAEventViewViewModel _vm = new();
        public string ViewTitle => "Export EA Event";
        public bool IsLoaded => _vm.IsLoaded;

        static readonly FilePickerFileType EaFileType = new("EA Event Files") { Patterns = new[] { "*.event" } };
        static readonly FilePickerFileType AllFileType = new("All Files") { Patterns = new[] { "*" } };

        public ToolExportEAEventView()
        {
            InitializeComponent();
            DataContext = _vm;
            _vm.IsLoading = true;
            _vm.Initialize();
            LoadMapList();
            _vm.IsLoading = false;
            _vm.MarkClean();
        }

        void LoadMapList()
        {
            try
            {
                var maps = MapSettingCore.MakeMapIDList();
                _vm.MapList.Clear();
                foreach (var m in maps)
                    _vm.MapList.Add(m.name);
            }
            catch (Exception ex)
            {
                Log.Error("ToolExportEAEventView.LoadMapList", ex.ToString());
            }
        }

        async System.Threading.Tasks.Task<string?> PickSaveFile(string suggestedName)
        {
            var file = await this.StorageProvider.SaveFilePickerAsync(new FilePickerSaveOptions
            {
                Title = "Export EA Event",
                SuggestedFileName = suggestedName,
                FileTypeChoices = new[] { EaFileType, AllFileType },
            });
            return file?.TryGetLocalPath();
        }

        /// <summary>Format ROM bytes as EA BYTE command with $ hex prefix.</summary>
        static string FormatBytesDollar(byte[] data, uint addr, uint length)
        {
            var sb = new StringBuilder();
            for (uint i = 0; i < length && (addr + i) < (uint)data.Length; i++)
            {
                if (i > 0) sb.Append(' ');
                sb.Append('$');
                sb.Append(data[addr + i].ToString("X2"));
            }
            return sb.ToString();
        }

        async void ExportEvents_Click(object? sender, RoutedEventArgs e)
        {
            var rom = CoreState.ROM;
            if (rom == null) return;

            int mapIndex = _vm.SelectedMapIndex;
            if (mapIndex < 0)
            {
                _vm.StatusText = "Please select a map first.";
                return;
            }

            try
            {
                // Get event address for the selected map using MapEventUnitCore
                uint eventAddr = MapEventUnitCore.GetEventAddrForMap(rom, (uint)mapIndex);
                if (!U.isSafetyOffset(eventAddr) || eventAddr == U.NOT_FOUND)
                {
                    _vm.StatusText = "Event address not found for this map.";
                    return;
                }

                string suggestedName = $"Map{mapIndex:D2}_Event_0x{eventAddr:X08}.event";
                string? path = await PickSaveFile(suggestedName);
                if (path == null) return;

                var sb = new StringBuilder();
                sb.AppendLine($"// Event export for Map {mapIndex} (0x{eventAddr:X08})");
                sb.AppendLine($"// Generated by FEBuilderGBA Avalonia");
                sb.AppendLine();

                // Export raw event data as ORG + BYTE blocks
                var ef = new ExportFunction();
                ef.Add($"Map{mapIndex}_Event", U.toPointer(eventAddr));
                ef.ExportEA(sb);

                // Write event data bytes
                uint dataLen = 0;
                for (uint i = 0; i < 0x10000 && (eventAddr + i) < (uint)rom.Data.Length; i += 4)
                {
                    uint val = rom.u32(eventAddr + i);
                    if (val == 0 && i > 0) { dataLen = i + 4; break; }
                }
                if (dataLen == 0) dataLen = 256; // fallback
                if (dataLen > 0)
                {
                    sb.AppendLine($"ORG {U.To0xHexString(eventAddr)}");
                    sb.AppendLine($"BYTE {FormatBytesDollar(rom.Data, eventAddr, dataLen)}");
                }

                File.WriteAllText(path, sb.ToString());
                _vm.StatusText = $"Exported events to: {Path.GetFileName(path)}";
            }
            catch (Exception ex)
            {
                Log.Error("ToolExportEAEventView.ExportEvents", ex.ToString());
                _vm.StatusText = $"Export failed: {ex.Message}";
            }
        }

        async void ExportWMapEvents_Click(object? sender, RoutedEventArgs e)
        {
            var rom = CoreState.ROM;
            if (rom == null) return;

            int mapIndex = _vm.SelectedMapIndex;
            if (mapIndex < 0)
            {
                _vm.StatusText = "Please select a map first.";
                return;
            }

            try
            {
                // Get world map event address from the stageclear pointer table
                uint wmapEventPtr = rom.RomInfo.worldmap_event_on_stageclear_pointer;
                if (wmapEventPtr == 0)
                {
                    _vm.StatusText = "World map events not available for this ROM version.";
                    return;
                }

                uint tableBase = rom.p32(wmapEventPtr);
                if (!U.isSafetyOffset(tableBase))
                {
                    _vm.StatusText = "World map event table not found.";
                    return;
                }

                uint addr = rom.p32(tableBase + (uint)(mapIndex * 4));
                if (!U.isSafetyOffset(addr) || addr == U.NOT_FOUND)
                {
                    _vm.StatusText = "No world map event found for this map.";
                    return;
                }

                string suggestedName = $"Map{mapIndex:D2}_WMap_0x{addr:X08}.event";
                string? path = await PickSaveFile(suggestedName);
                if (path == null) return;

                var sb = new StringBuilder();
                sb.AppendLine($"// World Map Event export for Map {mapIndex} (0x{addr:X08})");
                sb.AppendLine($"// Generated by FEBuilderGBA Avalonia");
                sb.AppendLine();

                var ef = new ExportFunction();
                ef.Add($"Map{mapIndex}_WorldMapEvent", U.toPointer(addr));
                ef.ExportEA(sb);

                File.WriteAllText(path, sb.ToString());
                _vm.StatusText = $"Exported world map events to: {Path.GetFileName(path)}";
            }
            catch (Exception ex)
            {
                Log.Error("ToolExportEAEventView.ExportWMapEvents", ex.ToString());
                _vm.StatusText = $"Export failed: {ex.Message}";
            }
        }

        async void ExportWMapEvents2_Click(object? sender, RoutedEventArgs e)
        {
            var rom = CoreState.ROM;
            if (rom == null || rom.RomInfo.version < 8)
            {
                _vm.StatusText = "World map event (selected) export is only available for FE8.";
                return;
            }

            int mapIndex = _vm.SelectedMapIndex;
            if (mapIndex < 0)
            {
                _vm.StatusText = "Please select a map first.";
                return;
            }

            try
            {
                // FE8 uses stageselect pointer for the second world map event table
                uint wmapSelectPtr = rom.RomInfo.worldmap_event_on_stageselect_pointer;
                if (wmapSelectPtr == 0)
                {
                    _vm.StatusText = "World map events (selected) not available.";
                    return;
                }

                uint tableBase = rom.p32(wmapSelectPtr);
                if (!U.isSafetyOffset(tableBase))
                {
                    _vm.StatusText = "World map event select table not found.";
                    return;
                }

                uint addr = rom.p32(tableBase + (uint)(mapIndex * 4));
                if (!U.isSafetyOffset(addr) || addr == U.NOT_FOUND)
                {
                    _vm.StatusText = "No selected world map event found.";
                    return;
                }

                string suggestedName = $"Map{mapIndex:D2}_WMap2_0x{addr:X08}.event";
                string? path = await PickSaveFile(suggestedName);
                if (path == null) return;

                var sb = new StringBuilder();
                sb.AppendLine($"// World Map Event (Selected) export for Map {mapIndex} (0x{addr:X08})");
                sb.AppendLine($"// Generated by FEBuilderGBA Avalonia");
                sb.AppendLine();

                var ef = new ExportFunction();
                ef.Add($"Map{mapIndex}_WorldMapEventSelect", U.toPointer(addr));
                ef.ExportEA(sb);

                File.WriteAllText(path, sb.ToString());
                _vm.StatusText = $"Exported world map events (selected) to: {Path.GetFileName(path)}";
            }
            catch (Exception ex)
            {
                Log.Error("ToolExportEAEventView.ExportWMapEvents2", ex.ToString());
                _vm.StatusText = $"Export failed: {ex.Message}";
            }
        }

        async void ExportMainTable_Click(object? sender, RoutedEventArgs e)
        {
            var rom = CoreState.ROM;
            if (rom == null) return;

            try
            {
                string? path = await PickSaveFile("MainTables.event");
                if (path == null) return;

                var sb = new StringBuilder();
                sb.AppendLine("// Main Table export");
                sb.AppendLine($"// ROM: {rom.RomInfo.VersionToFilename}");
                sb.AppendLine($"// Generated by FEBuilderGBA Avalonia");
                sb.AppendLine();

                // Export core tables using ExportFunction for key pointers
                var ef = new ExportFunction();

                // Unit table
                uint unitBase = rom.p32(rom.RomInfo.unit_pointer);
                if (U.isSafetyOffset(unitBase))
                    ef.Add("UnitTable", U.toPointer(unitBase));

                // Class table
                uint classBase = rom.p32(rom.RomInfo.class_pointer);
                if (U.isSafetyOffset(classBase))
                    ef.Add("ClassTable", U.toPointer(classBase));

                // Item table
                uint itemBase = rom.p32(rom.RomInfo.item_pointer);
                if (U.isSafetyOffset(itemBase))
                    ef.Add("ItemTable", U.toPointer(itemBase));

                ef.ExportEA(sb);
                sb.AppendLine();

                // Dump table data using StructExportCore for entry counts
                string[] tableNames = { "units", "classes", "items" };
                uint[] tableAddrs = { unitBase, classBase, itemBase };
                for (int t = 0; t < tableNames.Length; t++)
                {
                    uint baseAddr = tableAddrs[t];
                    if (!U.isSafetyOffset(baseAddr)) continue;

                    var tableDef = StructExportCore.GetTable(tableNames[t]);
                    if (tableDef == null) continue;

                    uint entryCount = tableDef.GetEntryCount(rom);
                    uint dataSize = tableDef.GetDataSize(rom);
                    uint totalSize = entryCount * dataSize;

                    sb.AppendLine($"// {tableNames[t]} data ({entryCount} entries, {dataSize} bytes each)");
                    sb.AppendLine($"ORG {U.To0xHexString(baseAddr)}");
                    sb.AppendLine($"BYTE {FormatBytesDollar(rom.Data, baseAddr, totalSize)}");
                    sb.AppendLine();
                }

                File.WriteAllText(path, sb.ToString());
                _vm.StatusText = $"Exported main tables to: {Path.GetFileName(path)}";
            }
            catch (Exception ex)
            {
                Log.Error("ToolExportEAEventView.ExportMainTable", ex.ToString());
                _vm.StatusText = $"Export failed: {ex.Message}";
            }
        }

        async void ExportUndoData_Click(object? sender, RoutedEventArgs e)
        {
            var rom = CoreState.ROM;
            var undo = CoreState.Undo;
            if (rom == null || undo == null) return;

            try
            {
                string? path = await PickSaveFile("UndoBuffer.event");
                if (path == null) return;

                var checkDupMap = new Dictionary<string, bool>();
                var revLines = new List<string>();

                // Iterate undo buffer from newest to oldest to avoid duplicates
                for (int i = undo.UndoBuffer.Count - 1; i >= 0; i--)
                {
                    Undo.UndoData undodata = undo.UndoBuffer[i];
                    bool isOutput = false;

                    for (int n = undodata.list.Count - 1; n >= 0; n--)
                    {
                        Undo.UndoPostion ud = undodata.list[n];
                        string key = ud.addr + "@" + ud.data.Length;
                        if (checkDupMap.ContainsKey(key))
                            continue;
                        checkDupMap[key] = true;

                        if (ud.data.Length >= 1024 * 1024 * 2)
                        {
                            revLines.Add("//SKIP THIS DATA 2M OVER");
                            continue;
                        }
                        revLines.Add("BYTE " + FormatBytesDollar(rom.Data, ud.addr, (uint)ud.data.Length) + ";");
                        revLines.Add("ORG $" + U.ToHexString(ud.addr));
                        isOutput = true;
                    }
                    if (isOutput)
                    {
                        revLines.Add("//" + undodata.name + undodata.time);
                    }
                }

                var sb = new StringBuilder();
                for (int i = revLines.Count - 1; i >= 0; i--)
                    sb.AppendLine(revLines[i]);

                File.WriteAllText(path, sb.ToString());
                _vm.StatusText = $"Exported undo buffer to: {Path.GetFileName(path)}";
            }
            catch (Exception ex)
            {
                Log.Error("ToolExportEAEventView.ExportUndoData", ex.ToString());
                _vm.StatusText = $"Export failed: {ex.Message}";
            }
        }

        public void NavigateTo(uint address) { }
        public void SelectFirstItem() { }
    }
}
