name: "E2E: FE8U"

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  workflow_dispatch:

permissions:
  contents: read
  checks: write

jobs:
  e2e:
    uses: ./.github/workflows/e2e-run.yml
    with:
      rom-name: FE8U
      job-name: "E2E FE8U"
      timeout: 30
    secrets: inherit
