name: "E2E: FE6"

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  workflow_dispatch:

permissions:
  contents: read
  checks: write

jobs:
  e2e:
    uses: ./.github/workflows/e2e-run.yml
    with:
      rom-name: FE6
      job-name: "E2E FE6"
      timeout: 15
    secrets: inherit
